name: Android CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Android SDK so Gradle can compile
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      - name: Install SDK packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # Install Gradle and GENERATE the wrapper in this repo
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Generate Gradle wrapper (if missing)
        run: gradle wrapper --gradle-version 8.8

      - name: Make wrapper executable
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
